<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="PatternList">
		<xs:sequence>
			<xs:element name="Pattern" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="ReportFileBanList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="FileNames" type="PatternList" minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="version" type="xs:positiveInteger" use="required" />
			<xs:attribute name="matchMode" type="xs:string" use="required" fixed="glob" />
			<xs:attribute name="caseSensitive" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>