<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RRDA.Plugins.DIG_3._1</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<PropertyGroup>
		<CopyToSharedArtifacts>true</CopyToSharedArtifacts>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RRDA.Core\RRDA.Core.csproj" />
    <ProjectReference Include="..\RRDA.Data\RRDA.Data.csproj" />
    <ProjectReference Include="..\RRDA.Plugins.Common\RRDA.Plugins.Common.csproj" />
  </ItemGroup>

</Project>
