<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5d3e82fb-3ece-4bc3-92de-970877abff0a</UserSecretsId>
  </PropertyGroup>
	
    <PropertyGroup>
	    <IISExpressWindowsAuthentication>enabled</IISExpressWindowsAuthentication>
	    <IISExpressAnonymousAuthentication>disabled</IISExpressAnonymousAuthentication>
    </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RRDA.Core\RRDA.Core.csproj" />
    <ProjectReference Include="..\RRDA.Data\RRDA.Data.csproj" />
    <ProjectReference Include="..\RRDA.Plugins.Common\RRDA.Plugins.Common.csproj" />
  </ItemGroup>

</Project>
