// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRDA.Data;

#nullable disable

namespace RRDA.Data.Migrations
{
    [DbContext(typeof(RRDADbContext))]
    [Migration("20260612083146_AddReportReferences")]
    partial class AddReportReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RRDA.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("WindowsUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("WindowsUsername")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("RRDA.Data.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("Operation", "OccurredAtUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("RRDA.Data.ReportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMaintenance")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportBatches");
                });

            modelBuilder.Entity("RRDA.Data.ReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ReportFileId")
                        .HasColumnType("int");

                    b.Property<string>("ReportSheet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReportFileId");

                    b.ToTable("ReportEntities", (string)null);
                });

            modelBuilder.Entity("RRDA.Data.ReportFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FileLastModify")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ReportBatchId")
                        .HasColumnType("int");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportBatchId");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("ReportFiles", (string)null);
                });

            modelBuilder.Entity("RRDA.Data.ReportProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSubjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReportEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportEntityId");

                    b.ToTable("ReportProperties", (string)null);
                });

            modelBuilder.Entity("RRDA.Data.ReportReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<int?>("SourceReportEntityId")
                        .HasColumnType("int");

                    b.Property<int>("SourceReportFileId")
                        .HasColumnType("int");

                    b.Property<string>("TargetKeyField")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetKeyValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("TargetReportFileId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetReportTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceReportEntityId")
                        .IsUnique()
                        .HasFilter("[SourceReportEntityId] IS NOT NULL");

                    b.HasIndex("SourceReportFileId");

                    b.HasIndex("TargetReportFileId");

                    b.HasIndex("SourceReportFileId", "TargetReportFileId")
                        .IsUnique()
                        .HasFilter("[TargetReportFileId] IS NOT NULL");

                    b.HasIndex("TargetReportTypeId", "TargetKeyValue");

                    b.ToTable("ReportReferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportReferences_ImportedShape", "[Origin] <> 0 OR ([SourceReportEntityId] IS NOT NULL AND [TargetReportTypeId] IS NOT NULL AND [TargetReportFileId] IS NULL AND [TargetKeyField] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ReportReferences_ManualShape", "[Origin] <> 1 OR ([SourceReportEntityId] IS NULL AND [TargetReportFileId] IS NOT NULL AND [TargetReportTypeId] IS NULL AND [TargetKeyField] IS NULL AND [TargetKeyValue] IS NULL)");
                        });
                });

            modelBuilder.Entity("RRDA.Data.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ReportTypes", (string)null);
                });

            modelBuilder.Entity("RRDA.Data.ReportEntity", b =>
                {
                    b.HasOne("RRDA.Data.ReportFile", "ReportFile")
                        .WithMany("Entities")
                        .HasForeignKey("ReportFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportFile");
                });

            modelBuilder.Entity("RRDA.Data.ReportFile", b =>
                {
                    b.HasOne("RRDA.Data.ReportBatch", "ReportBatch")
                        .WithMany("ReportFiles")
                        .HasForeignKey("ReportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RRDA.Data.ReportType", "ReportType")
                        .WithMany("Files")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportBatch");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("RRDA.Data.ReportProperty", b =>
                {
                    b.HasOne("RRDA.Data.ReportEntity", "ReportEntity")
                        .WithMany("Properties")
                        .HasForeignKey("ReportEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportEntity");
                });

            modelBuilder.Entity("RRDA.Data.ReportReference", b =>
                {
                    b.HasOne("RRDA.Data.ReportEntity", "SourceReportEntity")
                        .WithMany()
                        .HasForeignKey("SourceReportEntityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RRDA.Data.ReportFile", "SourceReportFile")
                        .WithMany("OutgoingReferences")
                        .HasForeignKey("SourceReportFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRDA.Data.ReportFile", "TargetReportFile")
                        .WithMany("IncomingManualReferences")
                        .HasForeignKey("TargetReportFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RRDA.Data.ReportType", "TargetReportType")
                        .WithMany()
                        .HasForeignKey("TargetReportTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceReportEntity");

                    b.Navigation("SourceReportFile");

                    b.Navigation("TargetReportFile");

                    b.Navigation("TargetReportType");
                });

            modelBuilder.Entity("RRDA.Data.ReportBatch", b =>
                {
                    b.Navigation("ReportFiles");
                });

            modelBuilder.Entity("RRDA.Data.ReportEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RRDA.Data.ReportFile", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("IncomingManualReferences");

                    b.Navigation("OutgoingReferences");
                });

            modelBuilder.Entity("RRDA.Data.ReportType", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
